services:
  - type: web
    name: myresume-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    # rootDir: src
    envVars:
      - key: NODE_ENV
        value: production
